### ISSUE TITLE
"Indexes are Invalid" Error

### ISSUE THREAD

**Issue by TCatapult** [Ristellise/garnet#1]
Hello! I'm trying to get this to work but keep getting the "indexes are invalid" error on the download file. In the config, do i enter in the link to the user i want to scrape, their username, or something else entirely? 

Thank you so much.

**Comment by Ristellise** [comment]
Hi! Thanks for the report. Looking at the code, I believe I goofed up somewhere.

I'm currently out for holidays so I'll check the issue once I'm back home.

**Comment by Ristellise** [comment]
> Hello! I'm trying to get this to work but keep getting the "indexes are invalid" error on the download file. In the config, do i enter in the link to the user i want to scrape, their username, or something else entirely?
> 
> Thank you so much.

Hi! I just checked the code more thoroughly.

First you will need to run `Indexer.py` to generate `index_new.json`. If the error appears that means the index is either empty or not found.

To answer your question, if the URL for fanbox looks like this: `https://inori-0.fanbox.cc/` the username is `inori-0` is what you enter into the YAML file.

For example:

```yaml
cookie: 'FANBOXSESSID CONTENT'
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/84.0.4147.105 Safari/537.36
users:
- inori-0
work-path: workspace
```

If the url looks like this: `https://www.fanbox.cc/@mikapikazo`, the sample will look like this:

```yaml
cookie: 'FANBOXSESSID CONTENT'
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/84.0.4147.105 Safari/537.36
users:
- mikapikazo
work-path: workspace
```

If you subscribed/support (Aka applied for a "Plan") to creators, you can use `~auto` to index all subscribed creators.
